### ISSUE TITLE
v2.6+ Reactivity System with Proxies & IE11 Compatibility

### ISSUE THREAD

**Issue by nxpatterns** [vuejs/roadmap#15]
According to https://stackoverflow.com/questions/45285992/es6-proxy-polyfill-for-ie11 there are no pollyfils for proxies in JavaScript; how far would the new reactivity system in VueJS v2.6+ will support IE11? 

Many thanks for your answers,..
kind regards

**For the sake of completeness:**
https://github.com/vuejs/roadmap/issues/3
https://github.com/vuejs/roadmap/issues/10

**Comment by posva** [comment]
2.x will still be compatible with IE. 3.x (using Proxies) will not.
Please, check closed issues for more info :)

**Comment by LinusBorg** [comment]
To add to this: 2.x will not use proxies,. 2.x-next (a parallel "experimental" branch) will, and 3 will likely make the complete switch

**Comment by nxpatterns** [comment]
**Understanding question:** Vue 3.X will be written in TypeScript and if I also develop my App with TypeScript, I can transpile it into ES5 easily? ES5 Support within IE11 is given (https://caniuse.com/#feat=es5). Therefore: Why is Vue 3.X not IE11 compatible? 

TypeScript would provide a way to use and transpile ES6 Proxies into ES5? 

**EDIT:** I've found a polyfill from google but I did not test it yet: https://github.com/GoogleChrome/proxy-polyfill

**Comment by LinusBorg** [comment]
Proxies have features that can't be emulated with ES5. 

As a Vue user, you are probably aware of the reactivity caveats, like not being able to detect changes to arrays when using bracket notation (`array[0] = new value'`).

Native proxies allow us to get rid of these limitations, but the aspects of `Proxy` that allow for this can't be expressed in ES5 - if they could, we wouldn't have the limitations on our reactivity system today.

**Comment by nxpatterns** [comment]
thank you very much!

**Comment by forresthopkinsa** [comment]
Is there going to be a *-next* release for 2.5?

**Comment by LinusBorg** [comment]
No. We'll tackle `next` after 2.6 has been released

**Comment by anthonygore** [comment]
@LinusBorg do you expect the switch to Proxies to improve performance/size as well, or is the aim just to eliminate reactivity caveats? Any advantage to using it in projects that already successfully navigate the current limitations?

**Comment by LinusBorg** [comment]
I think we might see performances in the sense of preventing more unnecessary rerenders. 

Right now, whenever any element in an array changes, for example, we have to run all watch era watching that array since we can't know if the dependeny only accessed a specific index - we can't track `array[0]` right now, as you know. 

We also will see a smaller built size as we can ship ES6 instead a ES5 since all supported browsers support it. 

We can't say anything Pacific about the actual performance of proxies vs. Getters/setters yet, but what we saw so far doesnt indicate any negative impact at least
