### ISSUE TITLE
Anything on the roadmap for Weex?

### ISSUE THREAD

**Issue by trainiac** [vuejs/roadmap#2]
Vue is the best, thank you! 

@yyx990803  What's happeing with Weex? As an avid user of Vue it feels like Weex hasn't gotten an official stamp off approval like that of Vuex or Vue-router.  I understand it's a much different undertaking but it seems like still a major factor for people deciding between React and Vue. React having React Native.

**Comment by yyx990803** [comment]
To clarify: Weex and Vue are two independent projects maintained by separate teams. Weex is an Apache Foundation project maintained by Alibaba, and is a very big project with multiple native rendering engines, multiple runtime frameworks and multiple tooling packages. There is a close collaboration between us and the Weex team at the runtime framework layer because Weex uses a build of Vue as its default runtime, but Weex is not part of Vue and we have separate roadmaps.

That said, the Weex team intends to invest more in community engagement in the coming months and we will also help them in those efforts.
